baseURL = "https://my-doc.com/"
languageCode = "en-us"
title = "MyDoc"

copyright = "All Rights Reserved"
googleAnalytics = "UA-54473959-1"

[params]
  title = "MyDoc"

[blackfriday]
    extensions = ["hardLineBreak"]

[menu]

  [[menu.main]]
    identifier = "blog"
    title = "Blog"
    url = "https://blog.my-doc.com/"
    weight = 4