baseURL = "https://my-doc.com/"
languageCode = "en-us"
title = "MyDoc"

copyright = "All Rights Reserved"

[params]
  title = "MyDoc"

sectionPagesMenu = "main"

[menu]

  [[menu.main]]
    identifier = "blog"
    title = "Blog"
    url = "https://blog.my-doc.com/"
    weight = 4